openapi: 3.0.0
info:
  title: Current API from ZITADEL
  version: v2
  description: This is the recommended API for ZITADEL if you start implementing a new project.
  contact:
    name: ZITADEL
    url: https://zitadel.com
    email: hi@zitadel.com
  license:
    name: Apache 2.0
    url: https://github.com/zitadel/zitadel/blob/main/LICENSE
servers:
  - url: https://{instanceName}.{region}.zitadel.cloud/
    variables:
      instanceName:
        default: demo
        description: Instance name assigned by ZITADEL Cloud
      region:
        enum:
          - 'us1'
          - 'eu1'
          - 'au1'
          - 'ch1'
        default: 'us1'
  - url: https://{instanceHost}/
    variables:
      instanceHost:
        default: demo.yourdomain.com
        description: Instance name assigned by ZITADEL Cloud
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: /.well-known/openid-configuration
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer