openapi: 3.0.0
info:
  title: Unified API
  description: Combined API for all services.
  version: 1.0.0
externalDocs:
  description: Detailed information about ZITADEL
  url: https://zitadel.com/docs
paths:
  /users:
    $ref: "../.artifacts/zitadel/user/v2/user_service.swagger.yaml#/paths"
  /sessions:
    $ref: "../.artifacts/zitadel/session/v2/session_service.swagger.yaml#/paths"
definitions:
  $ref: "../.artifacts/zitadel/user/v2/user_service.swagger.yaml#/definitions"