openapi: 3.0.0
info:
  title: Unified API
  description: Combined API for all services.
  version: 1.0.0
externalDocs:
  description: Detailed information about ZITADEL
  url: https://zitadel.com/docs
paths:
    $ref: "../.artifacts/zitadel.swagger.yaml#/paths"
definitions:
    $ref: "../.artifacts/zitadel.swagger.yaml#/definitions"