name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer:
    name: prepare devcontainer
    permissions:
        contents: read
        id-token: write
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: devcontainers/ci@v0.3
          with:
            push: never
            inheritEnv: true
            runCmd: pnpm install && pnpm build
        - run: ls -latr /workspaces/zitadel/console/