name: ffo test ci

on:
  push:
    branches:
      - test-depot

jobs:
  devcontainer:
    name: prepare devcontainer
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: depot/setup-action@v1
          with:
            oidc: true
        - run: devcontainer build --workspace-folder .