name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer: ## maybe add cache for npm and go here
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
          with:
            run_install: false
        - uses: actions/setup-node@v4
          with:
            cache: 'pnpm'
        - uses: actions/setup-go@v5
          with:
            go-version-file: 'go.mod'
        - uses: docker/login-action@v2 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: devcontainers/ci@v0.3
          with:
            runCmd: pnpm install && go mod download
            imageName: ghcr.io/zitadel/devcontainer
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: always
  build:
    needs: devcontainer
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v4
          with: 
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-
        - uses: devcontainers/ci@v0.3
          with:         
            runCmd: pnpm build
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: never
  test:
    needs: devcontainer
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: devcontainers/ci@v0.3
          with:         
            runCmd:  make core_build && make core_unit_test
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: never
  db-test:
    needs: devcontainer
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: devcontainers/ci@v0.3
          with:         
            runCmd:  make core_build && make core_integration_test
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: never