name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer:
    name: prepare devcontainer
    permissions:
        contents: read
        id-token: write
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: depot/use-action@v1
          with:
            project: f69z8v6840
        - uses: devcontainers/ci@v0.3
          with:
            imageName: registry.depot.dev/f69z8v6840
            cacheFrom: registry.depot.dev/f69z8v6840
            push: always
            runCmd: pnpm install && pnpm build
