name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer: ## maybe add cache for npm and go here
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: docker/login-action@v2 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: devcontainers/ci@v0.3
          with:
            imageName: ghcr.io/zitadel/devcontainer
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: always
  build:
    needs: devcontainer
    runs-on: depot-ubuntu-22.04-16
    steps:
        - uses: actions/checkout@v4
        - uses: devcontainers/ci@v0.3
          env:
            TURBO_API: TURBO_API
            TURBO_TOKEN: TURBO_TOKEN
            TURBO_TEAM: TURBO_TEAM
          with:         
            runCmd: pnpm install && pnpm build test integration
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: never