name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  build: ## maybe add cache for npm and go here
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: docker/login-action@v2 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: devcontainers/ci@v0.3
          with:
            imageName: ghcr.io/zitadel/devcontainer
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: always
            runCmd: pnpm install && pnpm build lint core#test:unit
        - uses: devcontainers/ci@v0.3
          with:
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: always
            runCmd: pnpm install && pnpm core#test:integration 