name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer:
    name: prepare devcontainer
    permissions:
        contents: read
        id-token: write
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: devcontainers/ci@v0.3
          with:    
            push: never
            runCmd: cd console && yarn install && yarn generate && yarn build
        # - run: npm install -g @devcontainers/cli
        # - uses: depot/use-action@v1
        #   with:
        #     project: f69z8v6840
        # - run: devcontainer build --workspace-folder .