name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer: ## maybe add cache for npm and go here
    runs-on: depot-ubuntu-22.04-8
    steps:
        - uses: actions/checkout@v4
        - uses: docker/login-action@v2 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: devcontainers/ci@v0.3
          with:
            imageName: ghcr.io/zitadel/devcontainer
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: always
  console:
    needs: devcontainer
    runs-on: depot-ubuntu-22.04-8
    defaults:
      run:
        working-directory: ./console
    steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v4
          with: 
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-
        - uses: devcontainers/ci@v0.3
          with:         
            runCmd: pnpm install && pnpm run lint build
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: never
  # test:
  #   needs: devcontainer
  #   runs-on: depot-ubuntu-22.04-8
  #   steps:
  #       - uses: actions/checkout@v4
  #       - uses: devcontainers/ci@v0.3
  #         with:         
  #           runCmd:  make core_build && make core_unit_test
  #           cacheFrom: ghcr.io/zitadel/devcontainer
  #           push: never
  # db-test:
  #   needs: devcontainer
  #   runs-on: depot-ubuntu-22.04-8
  #   steps:
  #       - uses: actions/checkout@v4
  #       - uses: devcontainers/ci@v0.3
  #         with:         
  #           runCmd:  make core_build && make core_integration_test
  #           cacheFrom: ghcr.io/zitadel/devcontainer
  #           push: never