name: ffo test ci

on:
  push:
    branches:
      - devcontainer-ci

jobs:
  devcontainer:
    name: prepare devcontainer
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
        - uses: docker/login-action@v2 
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/cache@v4
          with: 
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-
        - uses: devcontainers/ci@v0.3
          with:         
            runCmd: pnpm install && pnpm build
            imageName: ghcr.io/zitadel/devcontainer
            cacheFrom: ghcr.io/zitadel/devcontainer
            push: always
        - run: ls -latr console/dist/console